const fs = require('fs');

const tsContent = `import { Quiz } from './types';

export const QUIZZES: Quiz[] = [
  {
    id: 'q1',
    chapterId: 1,
    title: 'Intro to Psychology',
    titleKa: 'ფსიქოლოგიის შესავალი',
    titleRu: 'Введение в психологию',
    titleHy: 'Հոգեբանության ներածություն',
    questions: [
      {
        id: 'q1_1',
        question: 'What is the literal meaning of Psychology?',
        questionKa: 'რას ნიშნავს სიტყვასიტყვით ფსიქოლოგია?',
        questionRu: 'Что буквально означает слово «психология»?',
        questionHy: 'Ո՞րն է հոգեբանության բառացի նշանակությունը:',
        options: ['Study of mind', 'Study of behavior', 'Study of the soul', 'Study of brain'],
        optionsKa: ['გონების სწავლება', 'ქცევის სწავლება', 'სულის სწავლება', 'ტვინის სწავლება'],
        optionsRu: ['Изучение разума', 'Изучение поведения', 'Учение о душе', 'Изучение мозга'],
        optionsHy: ['Մտքի ուսումնասիրություն', 'Վարքագծի ուսումնասիրություն', 'Հոգու ուսումնասիրություն', 'Ուղեղի ուսումնասիրություն'],
        correctIndex: 2,
        explanation: 'The word comes from the Greek psyche (soul) and logos (study).',
        explanationKa: 'სიტყვა მომდინარეობს ბერძნული psyche (სული) და logos (სწავლება)-დან.',
        explanationRu: 'Слово происходит от греческих psyche (душа) и logos (учение).',
        explanationHy: 'Բառն առաջացել է հունարեն psyche (հոգի) և logos (ուսումնասիրություն) բառերից:'
      },
      {
        id: 'q1_2',
        question: 'Who is considered the father of modern psychology?',
        questionKa: 'ვინ ითვლება თანამედროვე ფსიქოლოგიის მამად?',
        questionRu: 'Кто считается отцом современной психологии?',
        questionHy: 'Ո՞վ է համարվում ժամանակակից հոգեբանության հայրը:',
        options: ['Sigmund Freud', 'Wilhelm Wundt', 'William James', 'B.F. Skinner'],
        optionsKa: ['ზიგმუნდ ფროიდი', 'ვილჰელმ ვუნდტი', 'უილიამ ჯეიმსი', 'ბ.ფ. სკინერი'],
        optionsRu: ['Зигмунд Фрейд', 'Вильгельм Вундт', 'Уильям Джеймс', 'Б.Ф. Скиннер'],
        optionsHy: ['Զիգմունդ Ֆրեյդ', 'Վիլհելմ Վունդտ', 'Ուիլյամ Ջեյմս', 'Բ.Ֆ. Սկիններ'],
        correctIndex: 1,
        explanation: 'Wilhelm Wundt established the first psychology laboratory in 1879.',
        explanationKa: 'ვილჰელმ ვუნდტმა დააარსა პირველი ფსიქოლოგიური ლაბორატორია 1879 წელს.',
        explanationRu: 'Вильгельм Вундт основал первую психологическую лабораторию в 1879 году.',
        explanationHy: 'Վիլհելմ Վունդտը հիմնադրել է առաջին հոգեբանական լաբորատորիան 1879 թվականին:'
      },
      {
        id: 'q1_3',
        question: 'Which psychological perspective emphasizes the role of the unconscious mind?',
        questionKa: 'რომელი ფსიქოლოგიური პერსპექტივა უსვამს ხაზს არაცნობიერი გონების როლს?',
        questionRu: 'Какая психологическая точка зрения подчеркивает роль бессознательного?',
        questionHy: 'Ո՞ր հոգեբանական տեսանկյունն է ընդգծում անգիտակցական մտքի դերը:',
        options: ['Behaviorism', 'Humanism', 'Psychoanalysis', 'Cognitive'],
        optionsKa: ['ბიჰევიორიზმი', 'ჰუმანიზმი', 'ფსიქოანალიზი', 'კოგნიტური'],
        optionsRu: ['Бихевиоризм', 'Гуманизм', 'Психоанализ', 'Когнитивная'],
        optionsHy: ['Վարքագծային', 'Հումանիզմ', 'Հոգեվերլուծություն', 'Ճանաչողական'],
        correctIndex: 2,
        explanation: 'Psychoanalysis, founded by Sigmund Freud, focuses on unconscious drives and conflicts.',
        explanationKa: 'ფსიქოანალიზი, რომელიც დააარსა ზიგმუნდ ფროიდმა, ფოკუსირებულია არაცნობიერ ლტოლვებსა და კონფლიქტებზე.',
        explanationRu: 'Психоанализ, основанный Зигмундом Фрейдом, фокусируется на бессознательных влечениях и конфликтах.',
        explanationHy: 'Հոգեվերլուծությունը, որը հիմնադրվել է Զիգմունդ Ֆրեյդի կողմից, կենտրոնանում է անգիտակցական դրդապատճառների և հակամարտությունների վրա:'
      },
      {
        id: 'q1_4',
        question: 'Behaviorism focuses solely on:',
        questionKa: 'ბიჰევიორიზმი ფოკუსირებულია მხოლოდ:',
        questionRu: 'Бихевиоризм сосредотачивается исключительно на:',
        questionHy: 'Բիհեյվիորիզմը կենտրոնանում է բացառապես.',
        options: ['Unconscious thoughts', 'Observable behavior', 'Emotional growth', 'Brain structures'],
        optionsKa: ['არაცნობიერ ფიქრებზე', 'დაკვირვებად ქცევაზე', 'ემოციურ ზრდაზე', 'ტვინის სტრუქტურებზე'],
        optionsRu: ['Бессознательных мыслях', 'Наблюдаемом поведении', 'Эмоциональном росте', 'Структурах мозга'],
        optionsHy: ['Անգիտակցական մտքերի', 'Դիտարկելի վարքի', 'Էմոցիոնալ աճի', 'Ուղեղի կառուցվածքների'],
        correctIndex: 1,
        explanation: 'Behaviorists believe psychology should only study observable, measurable behavior.',
        explanationKa: 'ბიჰევიორისტებს მიაჩნიათ, რომ ფსიქოლოგიამ უნდა შეისწავლოს მხოლოდ დაკვირვებადი და გაზომვადი ქცევა.',
        explanationRu: 'Бихевиористы считают, что психология должна изучать только наблюдаемое и измеримое поведение.',
        explanationHy: 'Բիհեյվիորիստները կարծում են, որ հոգեբանությունը պետք է ուսումնասիրի միայն դիտարկելի, չափելի վարքագիծը:'
      },
      {
        id: 'q1_5',
        question: 'What is the modern definition of psychology?',
        questionKa: 'რა არის ფსიქოლოგიის თანამედროვე განმარტება?',
        questionRu: 'Каково современное определение психологии?',
        questionHy: 'Ո՞րն է հոգեբանության ժամանակակից սահմանումը:',
        options: ['The study of the soul', 'The study of mental illness', 'The scientific study of behavior and mental processes', 'The study of human philosophy'],
        optionsKa: ['სულის შემსწავლელი მეცნიერება', 'ფსიქიკური დაავადებების შესწავლა', 'ქცევისა და მენტალური პროცესების მეცნიერული შესწავლა', 'ადამიანის ფილოსოფიის შესწავლა'],
        optionsRu: ['Изучение души', 'Изучение психических заболеваний', 'Научное изучение поведения и психических процессов', 'Изучение человеческой философии'],
        optionsHy: ['Հոգու ուսումնասիրություն', 'Հոգեկան հիվանդությունների ուսումնասիրություն', 'Վարքագծի և մտավոր գործընթացների գիտական ուսումնասիրություն', 'Մարդկային փիլիսոփայության ուսումնասիրություն'],
        correctIndex: 2,
        explanation: 'Today, psychology scientifically studies both observable behavior and internal mental processes.',
        explanationKa: 'დღეს ფსიქოლოგია მეცნიერულად სწავლობს როგორც დაკვირვებად ქცევას, ასევე შინაგან მენტალურ პროცესებს.',
        explanationRu: 'Сегодня психология научно изучает как наблюдаемое поведение, так и внутренние психические процессы.',
        explanationHy: 'Այսօր հոգեբանությունը գիտականորեն ուսումնասիրում է և՛ դիտելի վարքագիծը, և՛ ներքին մտավոր գործընթացները:'
      },
      {
        id: 'q1_6',
        question: 'Which research method involves an in-depth study of a single individual?',
        questionKa: 'რომელი კვლევის მეთოდი გულისხმობს ერთი ინდივიდის სიღრმისეულ შესწავლას?',
        questionRu: 'Какой метод исследования включает углубленное изучение одного человека?',
        questionHy: 'Ո՞ր հետազոտության մեթոդն է ներառում մեկ անհատի խորը ուսումնասիրություն:',
        options: ['Experiment', 'Survey', 'Case study', 'Naturalistic observation'],
        optionsKa: ['ექსპერიმენტი', 'გამოკითხვა', 'შემთხვევის შესწავლა (Case study)', 'ბუნებრივი დაკვირვება'],
        optionsRu: ['Эксперимент', 'Опрос', 'Тематическое исследование (Кейс-стади)', 'Естественное наблюдение'],
        optionsHy: ['Փորձ', 'Հարցում', 'Դեպքի ուսումնասիրություն', 'Բնական դիտարկում'],
        correctIndex: 2,
        explanation: 'A case study provides deep insights but details may not apply to everyone.',
        explanationKa: 'შემთხვევის შესწავლა გვაძლევს ღრმა ხედვას, მაგრამ დეტალები შეიძლება ყველას არ მიესადაგებოდეს.',
        explanationRu: 'Тематическое исследование дает глубокое понимание, но детали могут быть применимы не ко всем.',
        explanationHy: 'Դեպքի ուսումնասիրությունը տալիս է խորը պատկերացումներ, սակայն մանրամասները կարող են ոչ բոլորին վերաբերել:'
      },
      {
        id: 'q1_7',
        question: 'A testable prediction, often implied by a theory, is called a:',
        questionKa: 'შემოწმებად წინასწარმეტყველებას, რომელიც ხშირად თეორიიდან გამომდინარეობს, ეწოდება:',
        questionRu: 'Проверяемое предсказание, часто вытекающее из теории, называется:',
        questionHy: 'Ստուգելի կանխատեսումը, որը հաճախ ենթադրվում է տեսության կողմից, կոչվում է.',
        options: ['Variable', 'Hypothesis', 'Correlation', 'Fact'],
        optionsKa: ['ცვლადი', 'ჰიპოთეზა', 'კორელაცია', 'ფაქტი'],
        optionsRu: ['Переменная', 'Гипотеза', 'Корреляция', 'Факт'],
        optionsHy: ['Փոփոխական', 'Վարկած', 'Կորելացիա', 'Փաստ'],
        correctIndex: 1,
        explanation: 'A hypothesis is an educated guess that can be scientifically tested.',
        explanationKa: 'ჰიპოთეზა არის მეცნიერულად დასაბუთებული ვარაუდი, რომლის შემოწმებაც შესაძლებელია.',
        explanationRu: 'Гипотеза — это обоснованное предположение, которое можно научно проверить.',
        explanationHy: 'Վարկածը գիտականորեն հիմնավորված ենթադրություն է, որը կարող է ստուգվել:'
      },
      {
        id: 'q1_8',
        question: 'What does a correlation coefficient measure?',
        questionKa: 'რას ზომავს კორელაციის კოეფიციენტი?',
        questionRu: 'Что измеряет коэффициент корреляции?',
        questionHy: 'Ի՞նչ է չափում կորելացիայի գործակիցը:',
        options: ['Cause and effect', 'The degree of relationship between two variables', 'The average of a dataset', 'Brain wave activity'],
        optionsKa: ['მიზეზს და შედეგს', 'ორ ცვლადს შორის ურთიერთობის ხარისხს', 'მონაცემთა საშუალოს', 'ტვინის ტალღების აქტივობას'],
        optionsRu: ['Причину и следствие', 'Степень связи между двумя переменными', 'Среднее значение набора данных', 'Активность мозговых волн'],
        optionsHy: ['Պատճառ և հետևանք', 'Երկու փոփոխականների միջև կապի աստիճանը', 'Տվյալների բազայի միջինը', 'Ուղեղի ալիքների ակտիվությունը'],
        correctIndex: 1,
        explanation: 'Correlation describes how strongly two variables vary together, but does not imply causation.',
        explanationKa: 'კორელაცია აღწერს, თუ რამდენად ძლიერად იცვლება ორი ცვლადი ერთად, მაგრამ არ გულისხმობს მიზეზ-შედეგობრიობას.',
        explanationRu: 'Корреляция описывает, насколько сильно две переменные изменяются вместе, но не означает причинно-следственную связь.',
        explanationHy: 'Կորելացիան նկարագրում է, թե որքան ուժեղ են երկու փոփոխականները տատանվում միասին, բայց չի ենթադրում պատճառահետևանքային կապ:'
      },
      {
        id: 'q1_9',
        question: 'In an experiment, the variable that the researcher manipulates is the:',
        questionKa: 'ექსპერიმენტში ცვლადს, რომელსაც იკვლევს/მანიპულირებს მკვლევარი, ეწოდება:',
        questionRu: 'В эксперименте переменная, которой манипулирует исследователь, это:',
        questionHy: 'Փորձի ընթացքում փոփոխականը, որով մանիպուլյացիա է անում հետազոտողը, հետևյալն է.',
        options: ['Dependent variable', 'Confounding variable', 'Independent variable', 'Control variable'],
        optionsKa: ['დამოკიდებული ცვლადი', 'თანმხლები/დამაბრკოლებელი ცვლადი', 'დამოუკიდებელი ცვლადი', 'კონტროლის ცვლადი'],
        optionsRu: ['Зависимая переменная', 'Смешивающая переменная', 'Независимая переменная', 'Контрольная переменная'],
        optionsHy: ['Կախյալ փոփոխական', 'Շփոթեցնող փոփոխական', 'Անկախ փոփոխական', 'Վերահսկվող փոփոխական'],
        correctIndex: 2,
        explanation: 'The independent variable is the cause; the dependent variable is the measured effect.',
        explanationKa: 'დამოუკიდებელი ცვლადი არის მიზეზი; დამოკიდებული ცვლადი არის გაზომილი შედეგი.',
        explanationRu: 'Независимая переменная является причиной; зависимая переменная — измеряемым следствием.',
        explanationHy: 'Անկախ փոփոխականը պատճառն է. կախյալ փոփոխականը չափվող էֆեկտն է:'
      },
      {
        id: 'q1_10',
        question: 'The biopsychosocial approach integrates:',
        questionKa: 'ბიოფსიქოსოციალური მიდგომა აერთიანებს:',
        questionRu: 'Биопсихосоциальный подход объединяет:',
        questionHy: 'Բիոհոգեսոցիալական մոտեցումը միավորում է.',
        options: ['Only biological factors', 'Biological, psychological, and social-cultural factors', 'Psychological and unobservable factors', 'Social and cultural factors only'],
        optionsKa: ['მხოლოდ ბიოლოგიურ ფაქტორებს', 'ბიოლოგიურ, ფსიქოლოგიურ და სოციალურ-კულტურულ ფაქტორებს', 'ფსიქოლოგიურ და დაუკვირვებად ფაქტორებს', 'მხოლოდ სოციალურ და კულტურულ ფაქტორებს'],
        optionsRu: ['Только биологические факторы', 'Биологические, психологические и социокультурные факторы', 'Психологические и ненаблюдаемые факторы', 'Только социальные и культурные факторы'],
        optionsHy: ['Միայն կենսաբանական գործոններ', 'Կենսաբանական, հոգեբանական և սոցիալ-մշակութային գործոններ', 'Հոգեբանական և աննկատելի գործոններ', 'Միայն սոցիալական և մշակութային գործոններ'],
        correctIndex: 1,
        explanation: 'This integrated approach provides a more complete picture of behavior and mental processes.',
        explanationKa: 'ეს ინტეგრირებული მიდგომა გვაძლევს ქცევისა და მენტალური პროცესების უფრო სრულ სურათს.',
        explanationRu: 'Этот комплексный подход обеспечивает более полную картину поведения и психических процессов.',
        explanationHy: 'Այս ինտեգրված մոտեցումն ապահովում է վարքագծի և հոգեկան գործընթացների ավելի ամբողջական պատկեր:'
      },
      {
        id: 'q1_11',
        question: 'Which ethical principle requires telling participants about the study before they agree to participate?',
        questionKa: 'რომელი ეთიკური პრინციპი მოითხოვს მონაწილეების ინფორმირებას კვლევის შესახებ, სანამ ისინი დათანხმდებიან მონაწილეობაზე?',
        questionRu: 'Какое этическое правило требует информировать участников об исследовании до того, как они согласятся на участие?',
        questionHy: 'Ո՞ր էթիկական սկզբունքն է պահանջում մասնակիցներին պատմել ուսումնասիրության մասին մինչև նրանց մասնակցության համաձայնությունը:',
        options: ['Debriefing', 'Informed consent', 'Confidentiality', 'Deception'],
        optionsKa: ['დებრიფინგი', 'ინფორმირებული თანხმობა', 'კონფიდენციალურობა', 'მოტყუება'],
        optionsRu: ['Дебрифинг', 'Информированное согласие', 'Конфиденциальность', 'Обман'],
        optionsHy: ['Դեբրիֆինգ', 'Տեղեկացված համաձայնություն', 'Գաղտնիություն', 'Խաբեություն'],
        correctIndex: 1,
        explanation: 'Informed consent ensures participants are aware of any potential risks before participating.',
        explanationKa: 'ინფორმირებული თანხმობა უზრუნველყოფს, რომ მონაწილეებმა იცოდნენ პოტენციური რისკების შესახებ მონაწილეობამდე.',
        explanationRu: 'Информированное согласие гарантирует, что участники знают о возможных рисках до участия.',
        explanationHy: 'Տեղեկացված համաձայնությունը երաշխավորում է, որ մասնակիցները նախքան մասնակցելը տեղյակ են հնարավոր ռիսկերի մասին:'
      },
      {
        id: 'q1_12',
        question: 'Cognitive psychology is the study of:',
        questionKa: 'კოგნიტური ფსიქოლოგია სწავლობს:',
        questionRu: 'Когнитивная психология — это изучение:',
        questionHy: 'Ճանաչողական հոգեբանությունը ուսումնասիրությունն է.',
        options: ['How we behave in groups', 'Mental processes such as thinking, memory, and perception', 'Neurological structures', 'Animal behavior'],
        optionsKa: ['როგორ ვიქცევით ჯგუფებში', 'ისეთ მენტალურ პროცესებს, როგორიცაა აზროვნება, მეხსიერება და აღქმა', 'ნევროლოგიურ სტრუქტურებს', 'ცხოველთა ქცევას'],
        optionsRu: ['Того, как мы ведем себя в группах', 'Психических процессов, таких как мышление, память и восприятие', 'Неврологических структур', 'Поведения животных'],
        optionsHy: ['Թե ինչպես ենք մենք մեզ պահում խմբերում', 'Մտավոր գործընթացների, ինչպիսիք են մտածողությունը, հիշողությունը և ընկալումը', 'Նյարդաբանական կառույցներ', 'Կենդանիների վարքագիծ'],
        correctIndex: 1,
        explanation: 'The cognitive perspective focuses on how people encode, process, store, and retrieve information.',
        explanationKa: 'კოგნიტური პერსპექტივა ფოკუსირებულია იმაზე, თუ როგორ აღიქვამენ, ამუშავებენ, ინახავენ და აღადგენენ ადამიანები ინფორმაციას.',
        explanationRu: 'Когнитивная перспектива сосредотачивается на том, как люди кодируют, обрабатывают, хранят и извлекают информацию.',
        explanationHy: 'Ճանաչողական հեռանկարը կենտրոնանում է այն բանի վրա, թե ինչպես են մարդիկ կոդավորում, մշակում, պահպանում և առբերում տեղեկատվությունը:'
      },
      {
        id: 'q1_13',
        question: 'Explaining the purpose of the study to participants after it is over is known as:',
        questionKa: 'კვლევის დასრულების შემდეგ მონაწილეებისთვის მისი მიზნის ახსნას ეწოდება:',
        questionRu: 'Объяснение цели исследования участникам после его завершения называется:',
        questionHy: 'Մասնակիցներին հետազոտության նպատակի բացատրությունը դրա ավարտից հետո հայտնի է որպես.',
        options: ['Debriefing', 'Informed consent', 'Naturalistic observation', 'Double-blind procedure'],
        optionsKa: ['დებრიფინგი', 'ინფორმირებული თანხმობა', 'ბუნებრივი დაკვირვება', 'ორმაგი ბრმა პროცედურა'],
        optionsRu: ['Дебрифинг', 'Информированное согласие', 'Естественное наблюдение', 'Двойная слепая процедура'],
        optionsHy: ['Դեբրիֆինգ', 'Տեղեկացված համաձայնություն', 'Բնական դիտարկում', 'Կրկնակի կույր ընթացակարգ'],
        correctIndex: 0,
        explanation: 'Debriefing is a crucial ethical step, especially if the study involved any deception.',
        explanationKa: 'დებრიფინგი მნიშვნელოვანი ეთიკური ნაბიჯია, განსაკუთრებით მაშინ, თუ კვლევა შეიცავდა რაიმე სახის მოტყუებას.',
        explanationRu: 'Дебрифинг — важный этический шаг, особенно если в исследовании использовался обман.',
        explanationHy: 'Դեբրիֆինգը կարևոր էթիկական քայլ է, հատկապես, եթե ուսումնասիրությունը որևէ խաբեություն է պարունակում:'
      },
      {
        id: 'q1_14',
        question: 'Who was the first woman to earn a Ph.D. in psychology?',
        questionKa: 'ვინ იყო პირველი ქალი, რომელმაც მოიპოვა Ph.D. ხარისხი ფსიქოლოგიაში?',
        questionRu: 'Кто была первой женщиной, получившей степень доктора философии (Ph.D.) по психологии?',
        questionHy: 'Ո՞վ էր առաջին կինը, ով ստացավ հոգեբանության դոկտորի կոչում:',
        options: ['Mary Whiton Calkins', 'Margaret Floy Washburn', 'Dorothea Dix', 'Anna Freud'],
        optionsKa: ['მერი უიტონ კალკინსი', 'მარგარეტ ფლოი უოშბერნი', 'დოროთეა დიქსი', 'ანა ფროიდი'],
        optionsRu: ['Мэри Уитон Калкинс', 'Маргарет Флой Уошберн', 'Доротея Дикс', 'Анна Фрейд'],
        optionsHy: ['Մերի Ուիթոն Քալքինս', 'Մարգարետ Ֆլոյ Ուաշբերն', 'Դորոթեա Դիքս', 'Աննա Ֆրեյդ'],
        correctIndex: 1,
        explanation: 'Margaret Floy Washburn became the first woman to officially receive a psychology Ph.D. in 1894.',
        explanationKa: 'მარგარეტ ფლოი უოშბერნი გახდა პირველი ქალი, რომელმაც ოფიციალურად მიიღო Ph.D. ფსიქოლოგიაში 1894 წელს.',
        explanationRu: 'Маргарет Флой Уошберн стала первой женщиной, официально получившей степень доктора философии по психологии в 1894 году.',
        explanationHy: 'Մարգարետ Ֆլոյ Ուոշբերնը դարձավ առաջին կինը, ով պաշտոնապես ստացել է հոգեբանության դոկտորի կոչում 1894 թվականին:'
      },
      {
        id: 'q1_15',
        question: 'A random sample guarantees that:',
        questionKa: 'შემთხვევითი შერჩევა (Random sample) იძლევა გარანტიას, რომ:',
        questionRu: 'Случайная выборка гарантирует, что:',
        questionHy: 'Պատահական նմուշը երաշխավորում է, որ.',
        options: ['The sample is entirely unbiased', 'Every member of the population has an equal chance of being chosen', 'The exact cause and effect will be found', 'There will be no confounding variables'],
        optionsKa: ['შერჩევა აბსოლუტურად მიუკერძოებელია', 'პოპულაციის თითოეულ წევრს აქვს არჩევის თანაბარი შანსი', 'ზუსტი მიზეზი და შედეგი იქნება ნაპოვნი', 'არ იქნება დამაბრკოლებელი ცვლადები'],
        optionsRu: ['Выборка полностью непредвзята', 'Каждый член популяции имеет равные шансы быть выбранным', 'Будет найдена точная причина и следствие', 'Не будет смешивающих переменных'],
        optionsHy: ['Նմուշը լիովին անաչառ է', 'Բնակչության յուրաքանչյուր անդամ ունի ընտրվելու հավասար հնարավորություն', 'Կգտնվի ճշգրիտ պատճառն ու հետևանքը', 'Չեն լինի շփոթեցնող փոփոխականներ'],
        correctIndex: 1,
        explanation: 'Random sampling helps ensure the survey group accurately represents the wider population.',
        explanationKa: 'შემთხვევითი შერჩევა გვეხმარება უზრუნველვყოთ, რომ საკვლევი ჯგუფი ზუსტად წარმოადგენდეს ფართო პოპულაციას.',
        explanationRu: 'Случайная выборка помогает гарантировать, что группа опроса точно представляет более широкую популяцию.',
        explanationHy: 'Պատահական նմուշառումն օգնում է ապահովել, որ հարցվող խումբը ճշգրտորեն ներկայացնում է ավելի լայն բնակչությանը:'
      }
    ]
  }
];
`;

fs.writeFileSync('src/app/data/quizzes.ts', tsContent, 'utf-8');
console.log('Chapter 1 completely written!');
