$path = "src/app/data/book-data.ts"
$content = [System.IO.File]::ReadAllLines($path, [System.Text.Encoding]::UTF8)

# Questions 6-10
$content[576] = "        { id: 'q11-6', question: 'Locus of control relates to:', questionKa: 'კონტროლის ლოკუსი უკავშირდება:', options: ['Perceived control over events', 'Intelligence', 'Physical health', 'Memory capacity'], optionsKa: ['მოვლენებზე აღქმული კონტროლი', 'ინტელექტი', 'ფიზიკური ჯანმრთელობა', 'მეხსიერების მოცულობა'], correctIndex: 0, explanation: 'Internal vs external control.', explanationKa: 'შინაგანი თუ გარეგანი კონტროლი.' },"
$content[577] = "        { id: 'q11-7', question: 'Collective unconscious was proposed by:', questionKa: 'კოლექტიური არაცნობიერი შემოგვთავაზა:', options: ['Adler', 'Jung', 'Horney', 'Freud'], optionsKa: ['ადლერი', 'იუნგი', 'ჰორნი', 'ფროიდი'], correctIndex: 1, explanation: 'Jung introduced shared universal concepts.', explanationKa: 'იუნგმა შემოიტანა საერთო უნივერსალური ცნებები.' },"
$content[578] = "        { id: 'q11-8', question: 'Introversion vs extraversion is a:', questionKa: 'ინტროვერსია - ექსტრავერსია არის:', options: ['Defense mechanism', 'Trait dimension', 'Psychosexual stage', 'Social norm'], optionsKa: ['დაცვითი მექანიზმი', 'თვისების განსაზომილება', 'ფსიქოსექსუალური ეტაპი', 'სოციალური ნორმა'], correctIndex: 1, explanation: 'It is a central personality dimension.', explanationKa: 'ეს არის პიროვნების ცენტრალური განზომილება.' },"
$content[579] = "        { id: 'q11-9', question: 'Hierarchy of needs ends with:', questionKa: 'მოთხოვნილებათა იერარქია სრულდება:', options: ['Safety', 'Esteem', 'Self-actualization', 'Social belonging'], optionsKa: ['უსაფრთხოება', 'პატივისცემა', 'თვითაქტუალიზაცია', 'სოციალური კუთვნილება'], correctIndex: 2, explanation: 'Maslow placed self-actualization at top.', explanationKa: 'მასლოუმ თვითაქტუალიზაცია მწვერვალზე დააყენა.' },"
$content[580] = "        { id: 'q11-10', question: 'MMPI is used for:', questionKa: 'MMPI გამოიყენება:', options: ['Memory testing', 'Personality assessment', 'IQ testing', 'Vision screening'], optionsKa: ['მეხსიერების ტესტირება', 'პიროვნების შეფასება', 'IQ ტესტირება', 'მხედველობის შემოწმება'], correctIndex: 1, explanation: 'Minnesota Multiphasic Personality Inventory.', explanationKa: 'მინესოტის მრავალფაზიანი პიროვნების კითხვარი.' }"

[System.IO.File]::WriteAllLines($path, $content, [System.Text.Encoding]::UTF8)
