$path = "src/app/data/book-data.ts"
$content = [System.IO.File]::ReadAllLines($path, [System.Text.Encoding]::UTF8)

# Chapter 10 OptionsKa Fix
$content[561] = "        { id: 'q10-5', question: 'Ekman found emotions are:', questionKa: 'ეკმანმა აღმოაჩინა, რომ ემოციები არის:', options: ['Culturally unique', 'Universal', 'Only learned', 'Different everywhere'], optionsKa: ['კულტურულად უნიკალური', 'უნივერსალური', 'მხოლოდ დასწავლილი', 'ყველგან განსხვავებული'], correctIndex: 1, explanation: 'Basic expressions are universal.', explanationKa: 'ბაზისური გამომეტყველებები უნივერსალურია.' },"
$content[562] = "        { id: 'q10-6', question: 'Yerkes-Dodson law:', questionKa: 'იერკს-დოდსონის კანონი:', options: ['More arousal better', 'Moderate arousal optimal', 'Low arousal best', 'Arousal irrelevant'], optionsKa: ['მეტი აგზნება უკეთესია', 'ზომიერი აგზნება ოპტიმალურია', 'დაბალი აგზნება საუკეთესოა', 'აგზნება უმნიშვნელოა'], correctIndex: 1, explanation: 'Moderate arousal leads to optimal performance.', explanationKa: 'ზომიერი აგზნება იწვევს ოპტიმალურ შესრულებას.' },"
$content[563] = "        { id: 'q10-7', question: 'Cannon-Bard says:', questionKa: 'კენონ-ბარდის თეორია ამტკიცებს:', options: ['Body causes emotions', 'Emotions and arousal occur simultaneously', 'We label arousal', 'Emotions unnecessary'], optionsKa: ['', '', '', ''], correctIndex: 1, explanation: 'Experience and arousal happen simultaneously.', explanationKa: 'განცდა და აგზნება ერთდროულად ხდება.' },"
$content[563] = "        { id: 'q10-7', question: 'Cannon-Bard says:', questionKa: 'კენონ-ბარდის თეორია ამტკიცებს:', options: ['Body causes emotions', 'Emotions and arousal occur simultaneously', 'We label arousal', 'Emotions unnecessary'], optionsKa: ['სხეული იწვევს ემოციებს', 'ემოცია და აგზნება ერთდროულად ხდება', 'აგზნებას იარლიყს ვადებთ', 'ემოციები არ არის საჭირო'], correctIndex: 1, explanation: 'Experience and arousal happen simultaneously.', explanationKa: 'განცდა და აგზნება ერთდროულად ხდება.' },"
$content[564] = "        { id: 'q10-8', question: 'Overjustification effect:', questionKa: 'ზედმეტად გამართლების ეფექტი:', options: ['External rewards decrease intrinsic motivation', 'Too much motivation fails', 'More money more effort', 'Emotions too strong'], optionsKa: ['', '', '', ''], correctIndex: 0, explanation: 'External rewards can reduce intrinsic motivation.', explanationKa: 'გარე ჯილდომ შეიძლება შეამციროს შინაგანი მოტივაცია.' },"
$content[564] = "        { id: 'q10-8', question: 'Overjustification effect:', questionKa: 'ზედმეტად გამართლების ეფექტი:', options: ['External rewards decrease intrinsic motivation', 'Too much motivation fails', 'More money more effort', 'Emotions too strong'], optionsKa: ['გარე ჯილდოები ამცირებს შინაგან მოტივაციას', 'ზედმეტი მოტივაცია მარცხდება', 'მეტი ფული მეტი ძალისხმევა', 'ემოციები ძალიან ძლიერია'], correctIndex: 0, explanation: 'External rewards can reduce intrinsic motivation.', explanationKa: 'გარე ჯილდომ შეიძლება შეამციროს შინაგანი მოტივაცია.' },"
$content[565] = "        { id: 'q10-9', question: 'Which theory: label arousal to identify emotions?', questionKa: 'რომელი თეორია: აგზნების მარკირება ემოციების იდენტიფიცირებისთვის?', options: ['James-Lange', 'Cannon-Bard', 'Schachter-Singer', 'Evolutionary'], optionsKa: ['ჯეიმს-ლანგე', 'კენონ-ბარდი', 'შახტერ-ზინგერი', 'ევოლუციური'], correctIndex: 2, explanation: 'Emotion = arousal + cognitive label.', explanationKa: 'ემოცია = აგზნება + შემეცნებითი იარლიყი.' },"
$content[566] = "        { id: 'q10-10', question: 'Maslow is known for:', questionKa: 'მასლოუ ცნობილია:', options: ['Behaviorism', 'Hierarchy of needs', 'Psychoanalysis', 'CBT'], optionsKa: ['', '', '', ''], correctIndex: 1, explanation: 'The hierarchy of needs.', explanationKa: 'მოთხოვნილებათა იერარქია.' },"
$content[566] = "        { id: 'q10-10', question: 'Maslow is known for:', questionKa: 'მასლოუ ცნობილია:', options: ['', '', '', ''], optionsKa: ['ბიჰევიორიზმი', 'მოთხოვნილებათა იერარქია', 'ფსიქოანალიზი', 'კოგნიტურ-ბიჰევიორული თერაპია'], correctIndex: 1, explanation: 'The hierarchy of needs.', explanationKa: 'მოთხოვნილებათა იერარქია.' }"

[System.IO.File]::WriteAllLines($path, $content, [System.Text.Encoding]::UTF8)
